### PR TITLE
vary origin on delegated options

### LINKED ISSUE #291: Vary with dynamic config
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the regression has not already been reported

### Last working version

8.x.x

### Stopped working in version

9.x.x

### Node.js version

any

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

any

### 💥 Regression Report

this testcase has two different origins (example.com and sample.com):
https://github.com/fastify/fastify-cors/blob/3cf8f61d9358adb743d0a14bf575ffe3193ef4ea/test/cors.test.js#L126-L221

But does not add the Vary: origin header.

### Steps to Reproduce

add expectation that the vary header exists back to that test (and the other tests with config delegation changed in #288)

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by laat**
When the options used are delegated to a function, then the origin could be dynamic and should add `vary: origin` header.

The symbol usage feels a bit hacky, but the test changes should be ok.

fixes #291

#### Checklist

- [x] run `npm run test`
- [x] tests are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@saschanaz could you review as well? 

How much of this PR is reverting the original change?

**Comment by laat** [comment]
> How much of this PR is reverting the original change?

The spirit of the original change is still there, that when we have a static or '*' origin then we should not add the vary header. It's just that dynamic config through a callback can make the origin dynamic. The other dynamic config possibilities was handled in the original PR.

**Review by climba03003 — CHANGES_REQUESTED** [review]
Can you do another way round?
It should not add the `Vary` header by default, but instead when provide an option then add it.

File: index.js [hunk 1]
```diff
@@ -152,7 +158,7 @@ function normalizeCorsOptions (opts) {
 }
 
 function addCorsHeadersHandler (fastify, options, req, reply, next) {
```
Comment (climba03003) [inline index.js:160]: I would change the `normalizeCorsOptions` to provide extra argument.

```
function normalizeCorsOptions (opts, dynamic) {
  /* same as before */
  // use || false to always set to boolean
  corsOptions.dynamic = dynamic || false
}
```

**Review by climba03003 — CHANGES_REQUESTED** [review]

File: index.js (hunk 1 above)
Comment (laat) [reply index.js:160]: it's neither normalization nor does the property capture all related dynamic-ness.

If it's what you want, I can make the change.

Comment (climba03003) [reply index.js:160]: Maybe change to a proper name?
Split into two function seems unnecessary as both of them is internal helper function.

**Review by saschanaz — APPROVED** [review]
LGTM in terms of the behavior, as my intention of the patch was only for static options.

Sorry for the churn and thank you for the fix.

**Review by climba03003 — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

File: index.js [hunk 2]
```diff
@@ -128,15 +128,15 @@ function handleCorsOptionsCallbackDelegator (optionsResolver, fastify, req, repl
...
+      addCorsHeadersHandler(fastify, normalizeCorsOptions(options, true), req, reply, next)
     }
   })
 }
 
 /**
  * @param {import('./types').FastifyCorsOptions} opts
  */
-function normalizeCorsOptions (opts) {
+function normalizeCorsOptions (opts, dynamic) {
```
Comment (Eomm) [inline index.js:139]:
```suggest
function normalizeCorsOptions (opts, dynamic = false) {
```

File: index.js [hunk 3]
```diff
@@ -148,11 +148,12 @@ function normalizeCorsOptions (opts) {
     // strings are applied directly and any other value is ignored
     corsOptions.cacheControl = null
   }
+  corsOptions.dynamic = dynamic || false
```
Comment (Eomm) [inline index.js:151]: Late to the party:
why didn't we set it during the declaration?

**Comment by Uzlopak** [comment]
@Eomm 
You are little bit too late. It is already merged

**Comment by Eomm** [comment]
Yeah, but it is not released 😈

**Comment by mortenkjelling** [comment]
Can it be released soon though?

**Comment by mcollina** [comment]
shipped
